In [3]:
128703/3507132

0.03669750668067241

In [8]:
def one(dt):
    return '''
alter table factubt_userprofile_base_hour drop if exists partition (dt = '${{pre1_date}}-{dt}');'''.format(dt=dt)
dt_list = ['{}'.format(i).zfill(2) for i in range(0,24)]
s = []
for dt in dt_list:
    s.append(one(dt))
print(''.join(s))

alter table factubt_userprofile_base_hour drop if exists partition (dt = '${pre1_date}-00');
alter table factubt_userprofile_base_hour drop if exists partition (dt = '${pre1_date}-01');
alter table factubt_userprofile_base_hour drop if exists partition (dt = '${pre1_date}-02');
alter table factubt_userprofile_base_hour drop if exists partition (dt = '${pre1_date}-03');
alter table factubt_userprofile_base_hour drop if exists partition (dt = '${pre1_date}-04');
alter table factubt_userprofile_base_hour drop if exists partition (dt = '${pre1_date}-05');
alter table factubt_userprofile_base_hour drop if exists partition (dt = '${pre1_date}-06');
alter table factubt_userprofile_base_hour drop if exists partition (dt = '${pre1_date}-07');
alter table factubt_userprofile_base_hour drop if exists partition (dt = '${pre1_date}-08');
alter table factubt_userprofile_base_hour drop if exists partition (dt = '${pre1_date}-09');
alter table factubt_userprofile_base_hour drop if exists partition (dt = '${pre1_date}-10');
alter table factubt_userprofile_base_hour drop if exists partition (dt = '${pre1_date}-11');
alter table factubt_userprofile_base_hour drop if exists partition (dt = '${pre1_date}-12');
alter table factubt_userprofile_base_hour drop if exists partition (dt = '${pre1_date}-13');
alter table factubt_userprofile_base_hour drop if exists partition (dt = '${pre1_date}-14');
alter table factubt_userprofile_base_hour drop if exists partition (dt = '${pre1_date}-15');
alter table factubt_userprofile_base_hour drop if exists partition (dt = '${pre1_date}-16');
alter table factubt_userprofile_base_hour drop if exists partition (dt = '${pre1_date}-17');
alter table factubt_userprofile_base_hour drop if exists partition (dt = '${pre1_date}-18');
alter table factubt_userprofile_base_hour drop if exists partition (dt = '${pre1_date}-19');
alter table factubt_userprofile_base_hour drop if exists partition (dt = '${pre1_date}-20');
alter table factubt_userprofile_base_hour drop if exists partition (dt = '${pre1_date}-21');
alter table factubt_userprofile_base_hour drop if exists partition (dt = '${pre1_date}-22');
alter table factubt_userprofile_base_hour drop if exists partition (dt = '${pre1_date}-23');

In [16]:
print('\nunion all\n'.join(s))

select '2017-01-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2017-01-01',-2) and '2017-01-31'

union all

select '2017-02-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2017-02-01',-2) and '2017-02-31'

union all

select '2017-03-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2017-03-01',-2) and '2017-03-31'

union all

select '2017-04-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2017-04-01',-2) and '2017-04-31'

union all

select '2017-05-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2017-05-01',-2) and '2017-05-31'

union all

select '2017-06-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2017-06-01',-2) and '2017-06-31'

union all

select '2017-07-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2017-07-01',-2) and '2017-07-31'

union all

select '2017-08-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2017-08-01',-2) and '2017-08-31'

union all

select '2017-09-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2017-09-01',-2) and '2017-09-31'

union all

select '2017-10-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2017-10-01',-2) and '2017-10-31'

union all

select '2017-11-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2017-11-01',-2) and '2017-11-31'

union all

select '2017-12-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2017-12-01',-2) and '2017-12-31'

union all

select '2018-01-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2018-01-01',-2) and '2018-01-31'

union all

select '2018-02-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2018-02-01',-2) and '2018-02-31'

union all

select '2018-03-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2018-03-01',-2) and '2018-03-31'

union all

select '2018-04-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2018-04-01',-2) and '2018-04-31'

union all

select '2018-05-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2018-05-01',-2) and '2018-05-31'

union all

select '2018-06-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2018-06-01',-2) and '2018-06-31'

union all

select '2018-07-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2018-07-01',-2) and '2018-07-31'

union all

select '2018-08-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2018-08-01',-2) and '2018-08-31'

union all

select '2018-09-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2018-09-01',-2) and '2018-09-31'

union all

select '2018-10-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2018-10-01',-2) and '2018-10-31'

union all

select '2018-11-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2018-11-01',-2) and '2018-11-31'

union all

select '2018-12-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2018-12-01',-2) and '2018-12-31'

union all

select '2019-01-01' as d
,count(distinct uid) as uidcnt_pre3months
from ctripdi_prodb.triprepack_trips_v3
where d between add_months('2019-01-01',-2) and '2019-01-31'

In [19]:
import numpy as np
1/np.exp(0.0012*12)

0.9857031841224431